In [8]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

In [2]:
## Sentences
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'T am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'T am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
## One hot Representation for every word
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3693, 7421, 1545, 3566],
 [3693, 7421, 1545, 3526],
 [3693, 8206, 1545, 4248],
 [1272, 7012, 9654, 238, 9987],
 [9961, 7012, 9654, 238, 2700],
 [3580, 3693, 1132, 1545, 9517],
 [9535, 135, 1503, 238]]

In [7]:
## WordEmbedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3693 7421 1545 3566]
 [   0    0    0    0 3693 7421 1545 3526]
 [   0    0    0    0 3693 8206 1545 4248]
 [   0    0    0 1272 7012 9654  238 9987]
 [   0    0    0 9961 7012 9654  238 2700]
 [   0    0    0 3580 3693 1132 1545 9517]
 [   0    0    0    0 9535  135 1503  238]]


In [12]:
sent_length = 8
embedded_docs_pos = pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
print(embedded_docs_pos)

[[3693 7421 1545 3566    0    0    0    0]
 [3693 7421 1545 3526    0    0    0    0]
 [3693 8206 1545 4248    0    0    0    0]
 [1272 7012 9654  238 9987    0    0    0]
 [9961 7012 9654  238 2700    0    0    0]
 [3580 3693 1132 1545 9517    0    0    0]
 [9535  135 1503  238    0    0    0    0]]


In [13]:
## featurres representation
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 190ms/step


array([[[-0.00886209,  0.03954871, -0.00342954,  0.04248228,
          0.04573541,  0.02393616,  0.00725306,  0.03241371,
         -0.03981443,  0.01889512],
        [-0.00886209,  0.03954871, -0.00342954,  0.04248228,
          0.04573541,  0.02393616,  0.00725306,  0.03241371,
         -0.03981443,  0.01889512],
        [-0.00886209,  0.03954871, -0.00342954,  0.04248228,
          0.04573541,  0.02393616,  0.00725306,  0.03241371,
         -0.03981443,  0.01889512],
        [-0.00886209,  0.03954871, -0.00342954,  0.04248228,
          0.04573541,  0.02393616,  0.00725306,  0.03241371,
         -0.03981443,  0.01889512],
        [-0.03800122, -0.04911966, -0.01728223,  0.01377809,
         -0.03668817, -0.01381312,  0.01478272, -0.01909783,
          0.00322206, -0.02145549],
        [-0.02512844,  0.00516889,  0.01769057, -0.04397309,
         -0.04981118, -0.00283017,  0.04453341, -0.00577581,
         -0.00636204, -0.00642302],
        [-0.0180912 , -0.03916736,  0.04125426,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 3693, 7421, 1545, 3566])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 58ms/step


array([[-0.00886209,  0.03954871, -0.00342954,  0.04248228,  0.04573541,
         0.02393616,  0.00725306,  0.03241371, -0.03981443,  0.01889512],
       [-0.00886209,  0.03954871, -0.00342954,  0.04248228,  0.04573541,
         0.02393616,  0.00725306,  0.03241371, -0.03981443,  0.01889512],
       [-0.00886209,  0.03954871, -0.00342954,  0.04248228,  0.04573541,
         0.02393616,  0.00725306,  0.03241371, -0.03981443,  0.01889512],
       [-0.00886209,  0.03954871, -0.00342954,  0.04248228,  0.04573541,
         0.02393616,  0.00725306,  0.03241371, -0.03981443,  0.01889512],
       [-0.03800122, -0.04911966, -0.01728223,  0.01377809, -0.03668817,
        -0.01381312,  0.01478272, -0.01909783,  0.00322206, -0.02145549],
       [-0.02512844,  0.00516889,  0.01769057, -0.04397309, -0.04981118,
        -0.00283017,  0.04453341, -0.00577581, -0.00636204, -0.00642302],
       [-0.0180912 , -0.03916736,  0.04125426,  0.01845756,  0.03882917,
        -0.04433149,  0.01454177,  0.01314137

In [19]:
print("The End")

The End
